### ISSUE TITLE
"java.lang.RuntimeException: [was class java.util.zip.ZipException] invalid stored block lengths" on docx file

### ISSUE THREAD

**Issue by LLCampos** [matecat/MateCat-Filters#20]
Hi, 

[10724.docx](https://github.com/matecat/MateCat-Filters/files/674487/10724.docx)

This file is openable and readable using LibreOffice Writer, but when I tried to convert it to XLIFF I get the following:

```
[qtp1769597131-14] INFO com.matecat.converter.server.resources.ConvertToXliffResource - [CONVERSION REQUEST] 10724.docx:  to 
[qtp1769597131-14] INFO com.matecat.converter.core.project.ProjectFactory - [PROJECT CREATED] 10724.docx saved in /tmp/6171336572212321565
[qtp1769597131-14] INFO com.matecat.converter.core.okapiclient.OkapiClient - Using default segmentation
[qtp1769597131-14] INFO net.sf.okapi.common.pipelinedriver.PipelineDriver - Input: /tmp/6171336572212321565/10724.docx
[qtp1769597131-14] ERROR com.matecat.converter.server.resources.ConvertToXliffResource - [CONVERSION REQUEST FAILED] [was class java.util.zip.ZipException] invalid stored block lengths
java.lang.RuntimeException: [was class java.util.zip.ZipException] invalid stored block lengths
	at org.codehaus.stax2.ri.Stax2EventReaderImpl.throwUnchecked(Stax2EventReaderImpl.java:470)
	at org.codehaus.stax2.ri.Stax2EventReaderImpl.next(Stax2EventReaderImpl.java:262)
	at net.sf.okapi.filters.openxml.RunParser.processComplexCodes(RunParser.java:161)
	at net.sf.okapi.filters.openxml.RunParser.processRunBody(RunParser.java:148)
	at net.sf.okapi.filters.openxml.RunParser.parse(RunParser.java:79)
	at net.sf.okapi.filters.openxml.BlockParser.processRun(BlockParser.java:213)
	at net.sf.okapi.filters.openxml.BlockParser.parse(BlockParser.java:130)
	at net.sf.okapi.filters.openxml.StyledTextPartHandler.process(StyledTextPartHandler.java:139)
	at net.sf.okapi.filters.openxml.StyledTextPartHandler.open(StyledTextPartHandler.java:123)
	at net.sf.okapi.filters.openxml.StyledTextPartHandler.open(StyledTextPartHandler.java:115)
	at net.sf.okapi.filters.openxml.OpenXMLFilter.nextInZipFile(OpenXMLFilter.java:470)
	at net.sf.okapi.filters.openxml.OpenXMLFilter.next(OpenXMLFilter.java:262)
	at net.sf.okapi.filters.openxml.OpenXMLFilter.next(OpenXMLFilter.java:277)
	at net.sf.okapi.steps.common.RawDocumentToFilterEventsStep.handleEvent(RawDocumentToFilterEventsStep.java:171)
	at net.sf.okapi.common.pipeline.Pipeline.execute(Pipeline.java:123)
	at net.sf.okapi.common.pipeline.Pipeline.process(Pipeline.java:235)
	at net.sf.okapi.common.pipeline.Pipeline.process(Pipeline.java:205)
	at net.sf.okapi.common.pipelinedriver.PipelineDriver.processBatch(PipelineDriver.java:186)
	at com.matecat.converter.core.okapiclient.OkapiClient.generatePack(OkapiClient.java:343)
	at com.matecat.filters.basefilters.DefaultFilter.extractOkapiPack(DefaultFilter.java:56)
	at com.matecat.filters.basefilters.DefaultFilter.extract(DefaultFilter.java:35)
	at com.matecat.filters.basefilters.FiltersRouter.extract(FiltersRouter.java:36)
	at com.matecat.converter.server.resources.ConvertToXliffResource.convert(ConvertToXliffResource.java:90)
	at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
	at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:816)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:583)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1113)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1047)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:238)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:57)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.util.zip.ZipException: invalid stored block lengths
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at com.ctc.wstx.io.MergedReader.read(MergedReader.java:105)
	at com.ctc.wstx.io.ReaderSource.readInto(ReaderSource.java:86)
	at com.ctc.wstx.io.BranchingReaderSource.readInto(BranchingReaderSource.java:56)
	at com.ctc.wstx.sr.StreamScanner.loadMoreFromCurrent(StreamScanner.java:1060)
	at com.ctc.wstx.sr.StreamScanner.loadMoreFromCurrent(StreamScanner.java:1070)
	at com.ctc.wstx.sr.StreamScanner.getNextCharFromCurrent(StreamScanner.java:810)
	at com.ctc.wstx.sr.BasicStreamReader.readEndElem(BasicStreamReader.java:3162)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2831)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1073)
	at org.codehaus.stax2.ri.Stax2EventReaderImpl.nextEvent(Stax2EventReaderImpl.java:255)
	at org.codehaus.stax2.ri.Stax2EventReaderImpl.next(Stax2EventReaderImpl.java:260)
	... 65 more
```

Probably not a urgent problem but decided to report anyway. 

The file was created by a fuzzer built as a project of the Udacity's course on Software Testing.

**Comment by giusilvano** [comment]
Thank you LLCampos for having reported this! I'm sorry I couldn't reply sooner to this, holidays and super busy days in the middle... Anyway it seems a bug in the underlying Okapi Filter, I will check and forward this to Okapi ASAP.

**Comment by giusilvano** [comment]
I gave a second check to this, and the ZIP structure of the file (DOCXs are just ZIPs renamed) seems somehow corrupted. I can't even extract it using the Ubuntu's bundled ZIP extractor. My LibreOffice is able to read it too, but maybe because their ZIP library is more fault tolerant.
