### ISSUE TITLE
Exception running the command: java -cp ".:filters-1.2.5.jar" com.matecat.converter.Main

### ISSUE THREAD

**Issue by stevennt** [matecat/MateCat-Filters#33]
I have built as per the instruction in the wiki. All configurations were default: https://github.com/matecat/MateCat-Filters/wiki/Build-and-run

Running it produced the below exception. What could be the problem? Thanks in advance.

java -cp ".:filters-1.2.5.jar" com.matecat.converter.Main

Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.matecat.converter.server.MatecatConverterServer.<init>(MatecatConverterServer.java:47)
	at com.matecat.converter.Main.main(Main.java:21)
Caused by: java.lang.RuntimeException: Exception while loading config.properties.
	at com.matecat.converter.core.util.Config.<clinit>(Config.java:104)
	... 2 more
Caused by: java.lang.NullPointerException: inStream parameter is null
	at java.base/java.util.Objects.requireNonNull(Objects.java:246)
	at java.base/java.util.Properties.load(Properties.java:403)
	at com.matecat.converter.core.util.Config.<clinit>(Config.java:41)
	... 2 more

**Comment by AlexFalappa** [comment]
Hi @stevennt the stack trace you posted is usually shown when `config.properties` file is not found.

You should put the `config.properties` file in the same folder as the jar file and issue the launch command from there.

You can use `filters/src/main/resources/config.sample.properties` sample file as a start to create your own `config.properties`
